// Code generated by protoc-gen-go. DO NOT EDIT.
// source: contact.proto

package contact

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Contact_PhoneType int32

const (
	Contact_MOBILE Contact_PhoneType = 0
	Contact_HOME   Contact_PhoneType = 1
	Contact_WORK   Contact_PhoneType = 2
)

var Contact_PhoneType_name = map[int32]string{
	0: "MOBILE",
	1: "HOME",
	2: "WORK",
}

var Contact_PhoneType_value = map[string]int32{
	"MOBILE": 0,
	"HOME":   1,
	"WORK":   2,
}

func (x Contact_PhoneType) String() string {
	return proto.EnumName(Contact_PhoneType_name, int32(x))
}

func (Contact_PhoneType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{0, 0}
}

type Contact struct {
	FirstName            string                 `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string                 `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Uid                  int32                  `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Email                string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Phones               []*Contact_PhoneNumber `protobuf:"bytes,5,rep,name=phones,proto3" json:"phones,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Contact) Reset()         { *m = Contact{} }
func (m *Contact) String() string { return proto.CompactTextString(m) }
func (*Contact) ProtoMessage()    {}
func (*Contact) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{0}
}

func (m *Contact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contact.Unmarshal(m, b)
}
func (m *Contact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contact.Marshal(b, m, deterministic)
}
func (m *Contact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contact.Merge(m, src)
}
func (m *Contact) XXX_Size() int {
	return xxx_messageInfo_Contact.Size(m)
}
func (m *Contact) XXX_DiscardUnknown() {
	xxx_messageInfo_Contact.DiscardUnknown(m)
}

var xxx_messageInfo_Contact proto.InternalMessageInfo

func (m *Contact) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Contact) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Contact) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *Contact) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Contact) GetPhones() []*Contact_PhoneNumber {
	if m != nil {
		return m.Phones
	}
	return nil
}

type Contact_PhoneNumber struct {
	Number               string            `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Type                 Contact_PhoneType `protobuf:"varint,2,opt,name=type,proto3,enum=Contact_PhoneType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Contact_PhoneNumber) Reset()         { *m = Contact_PhoneNumber{} }
func (m *Contact_PhoneNumber) String() string { return proto.CompactTextString(m) }
func (*Contact_PhoneNumber) ProtoMessage()    {}
func (*Contact_PhoneNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{0, 0}
}

func (m *Contact_PhoneNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contact_PhoneNumber.Unmarshal(m, b)
}
func (m *Contact_PhoneNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contact_PhoneNumber.Marshal(b, m, deterministic)
}
func (m *Contact_PhoneNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contact_PhoneNumber.Merge(m, src)
}
func (m *Contact_PhoneNumber) XXX_Size() int {
	return xxx_messageInfo_Contact_PhoneNumber.Size(m)
}
func (m *Contact_PhoneNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_Contact_PhoneNumber.DiscardUnknown(m)
}

var xxx_messageInfo_Contact_PhoneNumber proto.InternalMessageInfo

func (m *Contact_PhoneNumber) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Contact_PhoneNumber) GetType() Contact_PhoneType {
	if m != nil {
		return m.Type
	}
	return Contact_MOBILE
}

type ContactList struct {
	Contact              []*Contact `protobuf:"bytes,1,rep,name=contact,proto3" json:"contact,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ContactList) Reset()         { *m = ContactList{} }
func (m *ContactList) String() string { return proto.CompactTextString(m) }
func (*ContactList) ProtoMessage()    {}
func (*ContactList) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{1}
}

func (m *ContactList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContactList.Unmarshal(m, b)
}
func (m *ContactList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContactList.Marshal(b, m, deterministic)
}
func (m *ContactList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContactList.Merge(m, src)
}
func (m *ContactList) XXX_Size() int {
	return xxx_messageInfo_ContactList.Size(m)
}
func (m *ContactList) XXX_DiscardUnknown() {
	xxx_messageInfo_ContactList.DiscardUnknown(m)
}

var xxx_messageInfo_ContactList proto.InternalMessageInfo

func (m *ContactList) GetContact() []*Contact {
	if m != nil {
		return m.Contact
	}
	return nil
}

func init() {
	proto.RegisterEnum("Contact_PhoneType", Contact_PhoneType_name, Contact_PhoneType_value)
	proto.RegisterType((*Contact)(nil), "Contact")
	proto.RegisterType((*Contact_PhoneNumber)(nil), "Contact.PhoneNumber")
	proto.RegisterType((*ContactList)(nil), "ContactList")
}

func init() {
	proto.RegisterFile("contact.proto", fileDescriptor_a5036fff2565fb15)
}

var fileDescriptor_a5036fff2565fb15 = []byte{
	// 293 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x5f, 0x4b, 0xc3, 0x30,
	0x14, 0xc5, 0xed, 0xfe, 0x74, 0xdb, 0x2d, 0x4a, 0x09, 0x43, 0xca, 0xf0, 0xa1, 0xf4, 0x41, 0x0a,
	0x4a, 0x8a, 0xf3, 0x41, 0x7c, 0x9d, 0x0c, 0x14, 0xd7, 0x55, 0x82, 0x20, 0xf8, 0xd6, 0x76, 0x71,
	0x8d, 0x2c, 0x4d, 0x69, 0x52, 0x61, 0x1f, 0xc4, 0xef, 0x2b, 0x4d, 0xb3, 0xa9, 0x6f, 0xe7, 0xfc,
	0x4e, 0x72, 0xef, 0xe1, 0xc2, 0x69, 0x2e, 0x4a, 0x95, 0xe6, 0x0a, 0x57, 0xb5, 0x50, 0x22, 0xf8,
	0xee, 0xc1, 0xe8, 0xa1, 0x23, 0xe8, 0x02, 0x26, 0x1f, 0xac, 0x96, 0x6a, 0x9d, 0x72, 0xea, 0x59,
	0xbe, 0x15, 0x4e, 0xc8, 0x2f, 0x40, 0x33, 0x18, 0xef, 0x52, 0x13, 0xf6, 0x74, 0x78, 0xf4, 0xc8,
	0x85, 0x7e, 0xc3, 0x36, 0x5e, 0xdf, 0xb7, 0xc2, 0x21, 0x69, 0x25, 0x9a, 0xc2, 0x90, 0xf2, 0x94,
	0xed, 0xbc, 0x81, 0x7e, 0xda, 0x19, 0x74, 0x0d, 0x76, 0x55, 0x88, 0x92, 0x4a, 0x6f, 0xe8, 0xf7,
	0x43, 0x67, 0x3e, 0xc5, 0x66, 0x37, 0x7e, 0x69, 0xf1, 0xba, 0xe1, 0x19, 0xad, 0x89, 0x79, 0x33,
	0x8b, 0xc1, 0xf9, 0x83, 0xd1, 0x39, 0xd8, 0xa5, 0x56, 0xa6, 0x9b, 0x71, 0xe8, 0x12, 0x06, 0x6a,
	0x5f, 0x75, 0xa5, 0xce, 0xe6, 0xe8, 0xff, 0xc8, 0xd7, 0x7d, 0x45, 0x89, 0xce, 0x83, 0x2b, 0x98,
	0x1c, 0x11, 0x02, 0xb0, 0xe3, 0x64, 0xf1, 0xb4, 0x5a, 0xba, 0x27, 0x68, 0x0c, 0x83, 0xc7, 0x24,
	0x5e, 0xba, 0x56, 0xab, 0xde, 0x12, 0xf2, 0xec, 0xf6, 0x82, 0x1b, 0x70, 0xcc, 0x9c, 0x15, 0x93,
	0x0a, 0x05, 0x30, 0x32, 0x77, 0xf3, 0x2c, 0xdd, 0x7c, 0x7c, 0x58, 0x43, 0x0e, 0xc1, 0xe2, 0xfe,
	0xfd, 0x6e, 0xcb, 0x54, 0xd1, 0x64, 0x38, 0x17, 0x3c, 0xca, 0xd8, 0x27, 0x95, 0x85, 0x90, 0xd1,
	0x56, 0x60, 0xce, 0xf2, 0x5a, 0x48, 0x5a, 0x7f, 0xb1, 0x9c, 0x4a, 0xbc, 0xa1, 0x5c, 0x44, 0xfa,
	0xfa, 0x91, 0xf9, 0x9a, 0xd9, 0xda, 0xde, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0xb5, 0x12, 0xfa,
	0x1e, 0x9d, 0x01, 0x00, 0x00,
}
